add gh_actions modifications and remove existing outputs

diff --git a/.github/workflows/test_colab.yml b/.github/workflows/test_colab.yml
--- a/.github/workflows/test_colab.yml
+++ b/.github/workflows/test_colab.yml
@@ -89,7 +89,7 @@ jobs:
           for nb in part1_prerequisites part2_searching_basics part3_exploring_cohorts; do
             docker run -d --name colab -v "$(pwd):/content" -e GOOGLE_APPLICATION_CREDENTIALS="${{ env.GOOGLE_APPLICATION_CREDENTIALS }}" imagingdatacommons/idc-testing-colab:latest
             docker exec -t colab /bin/bash -c "pip install papermill"
-            docker exec -t colab /bin/bash -c "set -o xtrace && set -o errexit && set -o pipefail && set -o nounset && set +o errexit && cd content/ && papermill /content/notebooks/getting_started/${nb}.ipynb /content/test/outputs/output_${nb}.ipynb && set -o errexit && ls -A"
+            docker exec -t colab /bin/bash -c "set -o xtrace && set -o errexit && set -o pipefail && set -o nounset && set +o errexit && cd content/ && papermill /content/notebooks/getting_started/${nb}.ipynb /content/test/outputs/${nb}_papermill_output.ipynb && set -o errexit && ls -A"
             #docker exec -t colab /bin/bash -c "jupyter nbconvert --to html --ExtractOutputPreprocessor.enabled=False /content/test/outputs/output_${nb}.ipynb"
             docker stop colab
             docker rm colab
@@ -103,15 +103,15 @@ jobs:
           file_pattern: 'test/*.csv test/outputs/*.ipynb'
           branch: 'master'
       
-      - name: Check output notebooks for errors 
-        run: | 
-          for nb in part1_prerequisites part2_searching_basics part3_exploring_cohorts; do
-            if grep -q '"name": "stderr"\|"status": "failed"' test/outputs/output_${nb}.ipynb; then
-              echo "Error messages found in the ${nb} notebook output:"
-              cat test/outputs/output_${nb}.ipynb
-              exit 1
-            else
-              echo "No errors found in the ${nb} notebook output."
-            fi
-          done
-          exit $EXIT_CODE
+      #- name: Check output notebooks for errors 
+      #  run: | 
+      #    for nb in part1_prerequisites part2_searching_basics part3_exploring_cohorts; do
+      #      if grep -q '"name": "stderr"\|"status": "failed"' test/outputs/output_${nb}.ipynb; then
+      #        echo "Error messages found in the ${nb} notebook output:"
+      #        cat test/outputs/output_${nb}.ipynb
+      #        exit 1
+      #      else
+      #        echo "No errors found in the ${nb} notebook output."
+      #      fi
+      #    done
+      #    exit $EXIT_CODE
